// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/orders/orders.proto

package go_micro_srv_orders

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderStatus int32

const (
	OrderStatus_AwaitingPayment   OrderStatus = 0
	OrderStatus_NoPayment         OrderStatus = 1
	OrderStatus_Cancelled         OrderStatus = 2
	OrderStatus_PaymentReceived   OrderStatus = 3
	OrderStatus_UnderPaid         OrderStatus = 4
	OrderStatus_ErrorSendingValue OrderStatus = 5
	OrderStatus_Completed         OrderStatus = 6
)

var OrderStatus_name = map[int32]string{
	0: "AwaitingPayment",
	1: "NoPayment",
	2: "Cancelled",
	3: "PaymentReceived",
	4: "UnderPaid",
	5: "ErrorSendingValue",
	6: "Completed",
}

var OrderStatus_value = map[string]int32{
	"AwaitingPayment":   0,
	"NoPayment":         1,
	"Cancelled":         2,
	"PaymentReceived":   3,
	"UnderPaid":         4,
	"ErrorSendingValue": 5,
	"Completed":         6,
}

func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}

func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{0}
}

type EmptyMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMessage) Reset()         { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()    {}
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{0}
}

func (m *EmptyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMessage.Unmarshal(m, b)
}
func (m *EmptyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMessage.Marshal(b, m, deterministic)
}
func (m *EmptyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMessage.Merge(m, src)
}
func (m *EmptyMessage) XXX_Size() int {
	return xxx_messageInfo_EmptyMessage.Size(m)
}
func (m *EmptyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMessage proto.InternalMessageInfo

type PlaceOrderRequest struct {
	Username             string            `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Product              string            `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Amount               float64           `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Details              map[string]string `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PlaceOrderRequest) Reset()         { *m = PlaceOrderRequest{} }
func (m *PlaceOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderRequest) ProtoMessage()    {}
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{1}
}

func (m *PlaceOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderRequest.Unmarshal(m, b)
}
func (m *PlaceOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderRequest.Marshal(b, m, deterministic)
}
func (m *PlaceOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderRequest.Merge(m, src)
}
func (m *PlaceOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderRequest.Size(m)
}
func (m *PlaceOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderRequest proto.InternalMessageInfo

func (m *PlaceOrderRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PlaceOrderRequest) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *PlaceOrderRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PlaceOrderRequest) GetDetails() map[string]string {
	if m != nil {
		return m.Details
	}
	return nil
}

type PlaceOrderResponse struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceOrderResponse) Reset()         { *m = PlaceOrderResponse{} }
func (m *PlaceOrderResponse) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderResponse) ProtoMessage()    {}
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{2}
}

func (m *PlaceOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderResponse.Unmarshal(m, b)
}
func (m *PlaceOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderResponse.Marshal(b, m, deterministic)
}
func (m *PlaceOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderResponse.Merge(m, src)
}
func (m *PlaceOrderResponse) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderResponse.Size(m)
}
func (m *PlaceOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderResponse proto.InternalMessageInfo

func (m *PlaceOrderResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type MarkOrderAsPaidRequest struct {
	OrderId              string            `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentMethod        string            `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount               float64           `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentDetails       map[string]string `protobuf:"bytes,4,rep,name=payment_details,json=paymentDetails,proto3" json:"payment_details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MarkOrderAsPaidRequest) Reset()         { *m = MarkOrderAsPaidRequest{} }
func (m *MarkOrderAsPaidRequest) String() string { return proto.CompactTextString(m) }
func (*MarkOrderAsPaidRequest) ProtoMessage()    {}
func (*MarkOrderAsPaidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{3}
}

func (m *MarkOrderAsPaidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkOrderAsPaidRequest.Unmarshal(m, b)
}
func (m *MarkOrderAsPaidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkOrderAsPaidRequest.Marshal(b, m, deterministic)
}
func (m *MarkOrderAsPaidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkOrderAsPaidRequest.Merge(m, src)
}
func (m *MarkOrderAsPaidRequest) XXX_Size() int {
	return xxx_messageInfo_MarkOrderAsPaidRequest.Size(m)
}
func (m *MarkOrderAsPaidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkOrderAsPaidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarkOrderAsPaidRequest proto.InternalMessageInfo

func (m *MarkOrderAsPaidRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *MarkOrderAsPaidRequest) GetPaymentMethod() string {
	if m != nil {
		return m.PaymentMethod
	}
	return ""
}

func (m *MarkOrderAsPaidRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *MarkOrderAsPaidRequest) GetPaymentDetails() map[string]string {
	if m != nil {
		return m.PaymentDetails
	}
	return nil
}

type GetOrdersRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Product              string   `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	SkipCount            int32    `protobuf:"varint,3,opt,name=skipCount,proto3" json:"skipCount,omitempty"`
	MaxResultCount       int32    `protobuf:"varint,4,opt,name=maxResultCount,proto3" json:"maxResultCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersRequest) Reset()         { *m = GetOrdersRequest{} }
func (m *GetOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrdersRequest) ProtoMessage()    {}
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{4}
}

func (m *GetOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersRequest.Unmarshal(m, b)
}
func (m *GetOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersRequest.Marshal(b, m, deterministic)
}
func (m *GetOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersRequest.Merge(m, src)
}
func (m *GetOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrdersRequest.Size(m)
}
func (m *GetOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersRequest proto.InternalMessageInfo

func (m *GetOrdersRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetOrdersRequest) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *GetOrdersRequest) GetSkipCount() int32 {
	if m != nil {
		return m.SkipCount
	}
	return 0
}

func (m *GetOrdersRequest) GetMaxResultCount() int32 {
	if m != nil {
		return m.MaxResultCount
	}
	return 0
}

type GetOrdersResponse struct {
	TotalCount           int64    `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Orders               []*Order `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersResponse) Reset()         { *m = GetOrdersResponse{} }
func (m *GetOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrdersResponse) ProtoMessage()    {}
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{5}
}

func (m *GetOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersResponse.Unmarshal(m, b)
}
func (m *GetOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersResponse.Marshal(b, m, deterministic)
}
func (m *GetOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersResponse.Merge(m, src)
}
func (m *GetOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrdersResponse.Size(m)
}
func (m *GetOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersResponse proto.InternalMessageInfo

func (m *GetOrdersResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *GetOrdersResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type Order struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string            `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Product              string            `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	Amount               float64           `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Date                 int64             `protobuf:"varint,5,opt,name=date,proto3" json:"date,omitempty"`
	Details              map[string]string `protobuf:"bytes,6,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Status               OrderStatus       `protobuf:"varint,7,opt,name=status,proto3,enum=go.micro.srv.orders.OrderStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{6}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Order) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *Order) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Order) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Order) GetDetails() map[string]string {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Order) GetStatus() OrderStatus {
	if m != nil {
		return m.Status
	}
	return OrderStatus_AwaitingPayment
}

type GetOrderRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderRequest) Reset()         { *m = GetOrderRequest{} }
func (m *GetOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderRequest) ProtoMessage()    {}
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{7}
}

func (m *GetOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderRequest.Unmarshal(m, b)
}
func (m *GetOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderRequest.Merge(m, src)
}
func (m *GetOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderRequest.Size(m)
}
func (m *GetOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderRequest proto.InternalMessageInfo

func (m *GetOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type GetOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderResponse) Reset()         { *m = GetOrderResponse{} }
func (m *GetOrderResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderResponse) ProtoMessage()    {}
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{8}
}

func (m *GetOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResponse.Unmarshal(m, b)
}
func (m *GetOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResponse.Marshal(b, m, deterministic)
}
func (m *GetOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResponse.Merge(m, src)
}
func (m *GetOrderResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderResponse.Size(m)
}
func (m *GetOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResponse proto.InternalMessageInfo

func (m *GetOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type ChangeStatusRequest struct {
	OrderId              string      `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status               OrderStatus `protobuf:"varint,2,opt,name=status,proto3,enum=go.micro.srv.orders.OrderStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChangeStatusRequest) Reset()         { *m = ChangeStatusRequest{} }
func (m *ChangeStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeStatusRequest) ProtoMessage()    {}
func (*ChangeStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{9}
}

func (m *ChangeStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeStatusRequest.Unmarshal(m, b)
}
func (m *ChangeStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeStatusRequest.Marshal(b, m, deterministic)
}
func (m *ChangeStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeStatusRequest.Merge(m, src)
}
func (m *ChangeStatusRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeStatusRequest.Size(m)
}
func (m *ChangeStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeStatusRequest proto.InternalMessageInfo

func (m *ChangeStatusRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *ChangeStatusRequest) GetStatus() OrderStatus {
	if m != nil {
		return m.Status
	}
	return OrderStatus_AwaitingPayment
}

func init() {
	proto.RegisterEnum("go.micro.srv.orders.OrderStatus", OrderStatus_name, OrderStatus_value)
	proto.RegisterType((*EmptyMessage)(nil), "go.micro.srv.orders.EmptyMessage")
	proto.RegisterType((*PlaceOrderRequest)(nil), "go.micro.srv.orders.PlaceOrderRequest")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.srv.orders.PlaceOrderRequest.DetailsEntry")
	proto.RegisterType((*PlaceOrderResponse)(nil), "go.micro.srv.orders.PlaceOrderResponse")
	proto.RegisterType((*MarkOrderAsPaidRequest)(nil), "go.micro.srv.orders.MarkOrderAsPaidRequest")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.srv.orders.MarkOrderAsPaidRequest.PaymentDetailsEntry")
	proto.RegisterType((*GetOrdersRequest)(nil), "go.micro.srv.orders.GetOrdersRequest")
	proto.RegisterType((*GetOrdersResponse)(nil), "go.micro.srv.orders.GetOrdersResponse")
	proto.RegisterType((*Order)(nil), "go.micro.srv.orders.Order")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.srv.orders.Order.DetailsEntry")
	proto.RegisterType((*GetOrderRequest)(nil), "go.micro.srv.orders.GetOrderRequest")
	proto.RegisterType((*GetOrderResponse)(nil), "go.micro.srv.orders.GetOrderResponse")
	proto.RegisterType((*ChangeStatusRequest)(nil), "go.micro.srv.orders.ChangeStatusRequest")
}

func init() { proto.RegisterFile("proto/orders/orders.proto", fileDescriptor_e484a55ca159a606) }

var fileDescriptor_e484a55ca159a606 = []byte{
	// 713 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0xed, 0xfc, 0x34, 0xd3, 0x36, 0x71, 0x37, 0xdf, 0x57, 0xb9, 0x11, 0x42, 0xc1, 0xa2,
	0x6d, 0x04, 0xc8, 0x45, 0xe9, 0x4d, 0xd5, 0x1b, 0x14, 0xa5, 0x15, 0xe2, 0x22, 0x50, 0xb9, 0x02,
	0x09, 0x09, 0x54, 0x2d, 0xd9, 0x55, 0x6a, 0xea, 0x3f, 0xbc, 0xeb, 0x42, 0x5e, 0x81, 0x0b, 0x5e,
	0x81, 0x77, 0xe0, 0xa1, 0xb8, 0xe2, 0x21, 0x90, 0xd7, 0x6b, 0xc7, 0x29, 0x4e, 0xd3, 0xaa, 0x57,
	0xf1, 0xcc, 0x9c, 0x99, 0x9c, 0x3d, 0x3b, 0x33, 0x0b, 0xdb, 0x61, 0x14, 0xf0, 0x60, 0x3f, 0x88,
	0x08, 0x8d, 0x98, 0xfc, 0xb1, 0x84, 0x0f, 0xb5, 0x27, 0x81, 0xe5, 0x39, 0xe3, 0x28, 0xb0, 0x58,
	0x74, 0x65, 0xa5, 0x21, 0xb3, 0x09, 0xeb, 0x27, 0x5e, 0xc8, 0xa7, 0x23, 0xca, 0x18, 0x9e, 0x50,
	0xf3, 0x8f, 0x02, 0x9b, 0xa7, 0x2e, 0x1e, 0xd3, 0x37, 0x49, 0xdc, 0xa6, 0x5f, 0x62, 0xca, 0x38,
	0xea, 0xc0, 0x6a, 0xcc, 0x68, 0xe4, 0x63, 0x8f, 0x1a, 0x4a, 0x57, 0xe9, 0x35, 0xec, 0xdc, 0x46,
	0x06, 0xd4, 0xc3, 0x28, 0x20, 0xf1, 0x98, 0x1b, 0xaa, 0x08, 0x65, 0x26, 0xda, 0x82, 0x1a, 0xf6,
	0x82, 0xd8, 0xe7, 0x46, 0xa5, 0xab, 0xf4, 0x14, 0x5b, 0x5a, 0x68, 0x04, 0x75, 0x42, 0x39, 0x76,
	0x5c, 0x66, 0x68, 0x5d, 0xad, 0xb7, 0xd6, 0x3f, 0xb0, 0x4a, 0xa8, 0x59, 0xff, 0xd0, 0xb0, 0x8e,
	0xd3, 0xac, 0x13, 0x9f, 0x47, 0x53, 0x3b, 0xab, 0xd1, 0x39, 0x82, 0xf5, 0x62, 0x00, 0xe9, 0xa0,
	0x5d, 0xd2, 0xa9, 0xe4, 0x99, 0x7c, 0xa2, 0xff, 0xa0, 0x7a, 0x85, 0xdd, 0x98, 0x4a, 0x82, 0xa9,
	0x71, 0xa4, 0x1e, 0x2a, 0xe6, 0x3e, 0xa0, 0xe2, 0xdf, 0xb0, 0x30, 0xf0, 0x19, 0x45, 0xdb, 0xb0,
	0x2a, 0x38, 0x9c, 0x3b, 0x44, 0x96, 0xa9, 0x0b, 0xfb, 0x15, 0x31, 0x7f, 0xaa, 0xb0, 0x35, 0xc2,
	0xd1, 0xa5, 0x48, 0x18, 0xb0, 0x53, 0xec, 0x90, 0x4c, 0xa4, 0xc5, 0x59, 0x68, 0x07, 0x9a, 0x21,
	0x9e, 0x7a, 0xd4, 0xe7, 0xe7, 0x1e, 0xe5, 0x17, 0x01, 0x91, 0x4c, 0x36, 0xa4, 0x77, 0x24, 0x9c,
	0x05, 0xc1, 0xb4, 0x39, 0xc1, 0x2e, 0xa0, 0x95, 0xa5, 0x67, 0xc2, 0x55, 0x84, 0x70, 0x2f, 0x4a,
	0x85, 0x2b, 0xe7, 0x67, 0x9d, 0xa6, 0x25, 0xe6, 0x44, 0xcc, 0x68, 0x49, 0x67, 0x67, 0x00, 0xed,
	0x12, 0xd8, 0x9d, 0x24, 0xfd, 0xa1, 0x80, 0xfe, 0x92, 0x72, 0x41, 0x80, 0xdd, 0xaf, 0x81, 0x1e,
	0x40, 0x83, 0x5d, 0x3a, 0xe1, 0x30, 0x97, 0xa4, 0x6a, 0xcf, 0x1c, 0x68, 0x17, 0x9a, 0x1e, 0xfe,
	0x66, 0x53, 0x16, 0xbb, 0x7c, 0x98, 0xb7, 0x59, 0xd5, 0xbe, 0xe6, 0x35, 0x27, 0xb0, 0x59, 0xe0,
	0x23, 0xaf, 0xf8, 0x21, 0x00, 0x0f, 0x38, 0x76, 0xd3, 0xc4, 0x84, 0x92, 0x66, 0x17, 0x3c, 0xa8,
	0x0f, 0xb5, 0x54, 0x4d, 0x43, 0x15, 0x4a, 0x77, 0x4a, 0x95, 0x4e, 0xdb, 0x46, 0x22, 0xcd, 0x5f,
	0x2a, 0x54, 0x85, 0x07, 0x35, 0x41, 0xcd, 0x9b, 0x40, 0x75, 0xc8, 0xdc, 0xf1, 0xd5, 0xc5, 0xc7,
	0xd7, 0x6e, 0x37, 0x3f, 0x08, 0x2a, 0x04, 0x73, 0x6a, 0x54, 0x05, 0x6b, 0xf1, 0x8d, 0x06, 0xb3,
	0x99, 0xaa, 0x09, 0xc2, 0x7b, 0x8b, 0x09, 0x97, 0xcf, 0x11, 0x3a, 0x84, 0x1a, 0xe3, 0x98, 0xc7,
	0xcc, 0xa8, 0x77, 0x95, 0x5e, 0xb3, 0xdf, 0x5d, 0x5c, 0xe1, 0x4c, 0xe0, 0x6c, 0x89, 0xbf, 0xd7,
	0x04, 0x3e, 0x83, 0x56, 0x76, 0x3b, 0xcb, 0x07, 0xc9, 0x3c, 0x9e, 0xf5, 0x56, 0x7e, 0x95, 0xcf,
	0xa1, 0x2a, 0xc2, 0x02, 0x7b, 0xf3, 0x4d, 0xa5, 0x40, 0xf3, 0x33, 0xb4, 0x87, 0x17, 0xd8, 0x9f,
	0x50, 0x79, 0x8e, 0xe5, 0x03, 0x3c, 0xd3, 0x46, 0xbd, 0x9b, 0x36, 0x4f, 0xbe, 0x2b, 0xb0, 0x56,
	0xf0, 0xa3, 0x36, 0xb4, 0x06, 0x5f, 0xb1, 0xc3, 0x1d, 0x7f, 0x22, 0x27, 0x4d, 0x5f, 0x41, 0x1b,
	0xd0, 0x78, 0x1d, 0x64, 0xa6, 0x92, 0x98, 0x43, 0xec, 0x8f, 0xa9, 0xeb, 0x52, 0xa2, 0xab, 0x49,
	0x8a, 0x8c, 0xd9, 0x74, 0x4c, 0x9d, 0x2b, 0x4a, 0x74, 0x2d, 0xc1, 0xbc, 0xf5, 0x09, 0x8d, 0x92,
	0x09, 0xd7, 0x2b, 0xe8, 0x7f, 0xd8, 0x3c, 0x89, 0xa2, 0x20, 0x3a, 0xa3, 0x3e, 0x71, 0xfc, 0xc9,
	0xbb, 0x44, 0x5f, 0xbd, 0x2a, 0x2a, 0x05, 0x5e, 0xe8, 0x52, 0x4e, 0x89, 0x5e, 0xeb, 0xff, 0xd6,
	0xa0, 0x96, 0x0e, 0x02, 0x3a, 0x07, 0x98, 0x6d, 0x3e, 0xb4, 0x7b, 0xbb, 0x0d, 0xdc, 0xd9, 0x5b,
	0x8a, 0x4b, 0x2f, 0xc5, 0x5c, 0x41, 0x63, 0x68, 0x5d, 0x5b, 0x44, 0xe8, 0xe9, 0x1d, 0xd6, 0x55,
	0xe7, 0x51, 0x29, 0x78, 0xee, 0xb1, 0x5a, 0x41, 0x1f, 0xa0, 0x91, 0xcf, 0x36, 0xda, 0x29, 0xcd,
	0xb8, 0xbe, 0x8b, 0x3a, 0xbb, 0xcb, 0x60, 0xf9, 0x11, 0xde, 0xc3, 0x6a, 0xe6, 0x46, 0x8f, 0x6f,
	0xcc, 0xca, 0x6a, 0xef, 0x2c, 0x41, 0xe5, 0xa5, 0x3f, 0xc2, 0x7a, 0xb1, 0x05, 0x51, 0xaf, 0x34,
	0xb1, 0xa4, 0x4b, 0x6f, 0xa5, 0xcb, 0xa7, 0x9a, 0x78, 0xf2, 0x0f, 0xfe, 0x06, 0x00, 0x00, 0xff,
	0xff, 0xb2, 0x71, 0xcf, 0x8c, 0x0f, 0x08, 0x00, 0x00,
}
