// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAccountUsers(t *testing.T) {
	t.Parallel()

	query := AccountUsers()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAccountUsersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccountUser{}
	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AccountUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAccountUsersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccountUser{}
	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := AccountUsers().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AccountUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAccountUsersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccountUser{}
	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AccountUserSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AccountUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAccountUsersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccountUser{}
	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AccountUserExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if AccountUser exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AccountUserExists to return true, but got false.")
	}
}

func testAccountUsersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccountUser{}
	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	accountUserFound, err := FindAccountUser(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if accountUserFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAccountUsersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccountUser{}
	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = AccountUsers().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAccountUsersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccountUser{}
	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := AccountUsers().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAccountUsersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	accountUserOne := &AccountUser{}
	accountUserTwo := &AccountUser{}
	if err = randomize.Struct(seed, accountUserOne, accountUserDBTypes, false, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}
	if err = randomize.Struct(seed, accountUserTwo, accountUserDBTypes, false, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = accountUserOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = accountUserTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AccountUsers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAccountUsersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	accountUserOne := &AccountUser{}
	accountUserTwo := &AccountUser{}
	if err = randomize.Struct(seed, accountUserOne, accountUserDBTypes, false, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}
	if err = randomize.Struct(seed, accountUserTwo, accountUserDBTypes, false, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = accountUserOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = accountUserTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AccountUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testAccountUsersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccountUser{}
	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AccountUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAccountUsersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccountUser{}
	if err = randomize.Struct(seed, o, accountUserDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(accountUserColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := AccountUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAccountUsersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccountUser{}
	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAccountUsersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccountUser{}
	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AccountUserSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAccountUsersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccountUser{}
	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AccountUsers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	accountUserDBTypes = map[string]string{`ID`: `character varying`, `Name`: `character varying`, `Username`: `character varying`, `PasswordHash`: `character varying`, `Email`: `character varying`, `PhoneNumber`: `character varying`, `Role`: `character varying`}
	_                  = bytes.MinRead
)

func testAccountUsersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(accountUserPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(accountUserAllColumns) == len(accountUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AccountUser{}
	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AccountUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAccountUsersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(accountUserAllColumns) == len(accountUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AccountUser{}
	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AccountUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, accountUserDBTypes, true, accountUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(accountUserAllColumns, accountUserPrimaryKeyColumns) {
		fields = accountUserAllColumns
	} else {
		fields = strmangle.SetComplement(
			accountUserAllColumns,
			accountUserPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AccountUserSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAccountUsersUpsert(t *testing.T) {
	t.Parallel()

	if len(accountUserAllColumns) == len(accountUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := AccountUser{}
	if err = randomize.Struct(seed, &o, accountUserDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AccountUser: %s", err)
	}

	count, err := AccountUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, accountUserDBTypes, false, accountUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AccountUser struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AccountUser: %s", err)
	}

	count, err = AccountUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
