// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testProviders(t *testing.T) {
	t.Parallel()

	query := Providers()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testProvidersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Provider{}
	if err = randomize.Struct(seed, o, providerDBTypes, true, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Providers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testProvidersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Provider{}
	if err = randomize.Struct(seed, o, providerDBTypes, true, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Providers().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Providers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testProvidersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Provider{}
	if err = randomize.Struct(seed, o, providerDBTypes, true, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ProviderSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Providers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testProvidersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Provider{}
	if err = randomize.Struct(seed, o, providerDBTypes, true, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ProviderExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Provider exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ProviderExists to return true, but got false.")
	}
}

func testProvidersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Provider{}
	if err = randomize.Struct(seed, o, providerDBTypes, true, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	providerFound, err := FindProvider(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if providerFound == nil {
		t.Error("want a record, got nil")
	}
}

func testProvidersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Provider{}
	if err = randomize.Struct(seed, o, providerDBTypes, true, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Providers().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testProvidersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Provider{}
	if err = randomize.Struct(seed, o, providerDBTypes, true, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Providers().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testProvidersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	providerOne := &Provider{}
	providerTwo := &Provider{}
	if err = randomize.Struct(seed, providerOne, providerDBTypes, false, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}
	if err = randomize.Struct(seed, providerTwo, providerDBTypes, false, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = providerOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = providerTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Providers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testProvidersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	providerOne := &Provider{}
	providerTwo := &Provider{}
	if err = randomize.Struct(seed, providerOne, providerDBTypes, false, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}
	if err = randomize.Struct(seed, providerTwo, providerDBTypes, false, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = providerOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = providerTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Providers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testProvidersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Provider{}
	if err = randomize.Struct(seed, o, providerDBTypes, true, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Providers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testProvidersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Provider{}
	if err = randomize.Struct(seed, o, providerDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(providerColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Providers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testProvidersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Provider{}
	if err = randomize.Struct(seed, o, providerDBTypes, true, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testProvidersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Provider{}
	if err = randomize.Struct(seed, o, providerDBTypes, true, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ProviderSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testProvidersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Provider{}
	if err = randomize.Struct(seed, o, providerDBTypes, true, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Providers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	providerDBTypes = map[string]string{`ID`: `character varying`, `Name`: `character varying`, `Logo`: `character varying`, `Status`: `integer`, `Discount`: `double precision`}
	_               = bytes.MinRead
)

func testProvidersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(providerPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(providerAllColumns) == len(providerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Provider{}
	if err = randomize.Struct(seed, o, providerDBTypes, true, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Providers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, providerDBTypes, true, providerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testProvidersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(providerAllColumns) == len(providerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Provider{}
	if err = randomize.Struct(seed, o, providerDBTypes, true, providerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Providers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, providerDBTypes, true, providerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(providerAllColumns, providerPrimaryKeyColumns) {
		fields = providerAllColumns
	} else {
		fields = strmangle.SetComplement(
			providerAllColumns,
			providerPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ProviderSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testProvidersUpsert(t *testing.T) {
	t.Parallel()

	if len(providerAllColumns) == len(providerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Provider{}
	if err = randomize.Struct(seed, &o, providerDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Provider: %s", err)
	}

	count, err := Providers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, providerDBTypes, false, providerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Provider struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Provider: %s", err)
	}

	count, err = Providers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
