// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// ProviderCountry is an object representing the database table.
type ProviderCountry struct {
	ProviderID string `boil:"provider_id" json:"provider_id" toml:"provider_id" yaml:"provider_id"`
	CountryID  string `boil:"country_id" json:"country_id" toml:"country_id" yaml:"country_id"`

	R *providerCountryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L providerCountryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ProviderCountryColumns = struct {
	ProviderID string
	CountryID  string
}{
	ProviderID: "provider_id",
	CountryID:  "country_id",
}

// Generated where

var ProviderCountryWhere = struct {
	ProviderID whereHelperstring
	CountryID  whereHelperstring
}{
	ProviderID: whereHelperstring{field: "\"provider_country\".\"provider_id\""},
	CountryID:  whereHelperstring{field: "\"provider_country\".\"country_id\""},
}

// ProviderCountryRels is where relationship names are stored.
var ProviderCountryRels = struct {
}{}

// providerCountryR is where relationships are stored.
type providerCountryR struct {
}

// NewStruct creates a new relationship struct
func (*providerCountryR) NewStruct() *providerCountryR {
	return &providerCountryR{}
}

// providerCountryL is where Load methods for each relationship are stored.
type providerCountryL struct{}

var (
	providerCountryAllColumns            = []string{"provider_id", "country_id"}
	providerCountryColumnsWithoutDefault = []string{"provider_id", "country_id"}
	providerCountryColumnsWithDefault    = []string{}
	providerCountryPrimaryKeyColumns     = []string{"provider_id", "country_id"}
)

type (
	// ProviderCountrySlice is an alias for a slice of pointers to ProviderCountry.
	// This should generally be used opposed to []ProviderCountry.
	ProviderCountrySlice []*ProviderCountry

	providerCountryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	providerCountryType                 = reflect.TypeOf(&ProviderCountry{})
	providerCountryMapping              = queries.MakeStructMapping(providerCountryType)
	providerCountryPrimaryKeyMapping, _ = queries.BindMapping(providerCountryType, providerCountryMapping, providerCountryPrimaryKeyColumns)
	providerCountryInsertCacheMut       sync.RWMutex
	providerCountryInsertCache          = make(map[string]insertCache)
	providerCountryUpdateCacheMut       sync.RWMutex
	providerCountryUpdateCache          = make(map[string]updateCache)
	providerCountryUpsertCacheMut       sync.RWMutex
	providerCountryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single providerCountry record from the query.
func (q providerCountryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ProviderCountry, error) {
	o := &ProviderCountry{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for provider_country")
	}

	return o, nil
}

// All returns all ProviderCountry records from the query.
func (q providerCountryQuery) All(ctx context.Context, exec boil.ContextExecutor) (ProviderCountrySlice, error) {
	var o []*ProviderCountry

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ProviderCountry slice")
	}

	return o, nil
}

// Count returns the count of all ProviderCountry records in the query.
func (q providerCountryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count provider_country rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q providerCountryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if provider_country exists")
	}

	return count > 0, nil
}

// ProviderCountries retrieves all the records using an executor.
func ProviderCountries(mods ...qm.QueryMod) providerCountryQuery {
	mods = append(mods, qm.From("\"provider_country\""))
	return providerCountryQuery{NewQuery(mods...)}
}

// FindProviderCountry retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindProviderCountry(ctx context.Context, exec boil.ContextExecutor, providerID string, countryID string, selectCols ...string) (*ProviderCountry, error) {
	providerCountryObj := &ProviderCountry{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"provider_country\" where \"provider_id\"=$1 AND \"country_id\"=$2", sel,
	)

	q := queries.Raw(query, providerID, countryID)

	err := q.Bind(ctx, exec, providerCountryObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from provider_country")
	}

	return providerCountryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ProviderCountry) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no provider_country provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(providerCountryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	providerCountryInsertCacheMut.RLock()
	cache, cached := providerCountryInsertCache[key]
	providerCountryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			providerCountryAllColumns,
			providerCountryColumnsWithDefault,
			providerCountryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(providerCountryType, providerCountryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(providerCountryType, providerCountryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"provider_country\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"provider_country\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into provider_country")
	}

	if !cached {
		providerCountryInsertCacheMut.Lock()
		providerCountryInsertCache[key] = cache
		providerCountryInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the ProviderCountry.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ProviderCountry) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	providerCountryUpdateCacheMut.RLock()
	cache, cached := providerCountryUpdateCache[key]
	providerCountryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			providerCountryAllColumns,
			providerCountryPrimaryKeyColumns,
		)

		if len(wl) == 0 {
			return 0, errors.New("models: unable to update provider_country, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"provider_country\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, providerCountryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(providerCountryType, providerCountryMapping, append(wl, providerCountryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update provider_country row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for provider_country")
	}

	if !cached {
		providerCountryUpdateCacheMut.Lock()
		providerCountryUpdateCache[key] = cache
		providerCountryUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q providerCountryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for provider_country")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for provider_country")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ProviderCountrySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), providerCountryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"provider_country\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, providerCountryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in providerCountry slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all providerCountry")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ProviderCountry) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no provider_country provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(providerCountryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	providerCountryUpsertCacheMut.RLock()
	cache, cached := providerCountryUpsertCache[key]
	providerCountryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			providerCountryAllColumns,
			providerCountryColumnsWithDefault,
			providerCountryColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			providerCountryAllColumns,
			providerCountryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert provider_country, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(providerCountryPrimaryKeyColumns))
			copy(conflict, providerCountryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"provider_country\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(providerCountryType, providerCountryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(providerCountryType, providerCountryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert provider_country")
	}

	if !cached {
		providerCountryUpsertCacheMut.Lock()
		providerCountryUpsertCache[key] = cache
		providerCountryUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single ProviderCountry record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ProviderCountry) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ProviderCountry provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), providerCountryPrimaryKeyMapping)
	sql := "DELETE FROM \"provider_country\" WHERE \"provider_id\"=$1 AND \"country_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from provider_country")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for provider_country")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q providerCountryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no providerCountryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from provider_country")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for provider_country")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ProviderCountrySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), providerCountryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"provider_country\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, providerCountryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from providerCountry slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for provider_country")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ProviderCountry) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindProviderCountry(ctx, exec, o.ProviderID, o.CountryID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProviderCountrySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ProviderCountrySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), providerCountryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"provider_country\".* FROM \"provider_country\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, providerCountryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ProviderCountrySlice")
	}

	*o = slice

	return nil
}

// ProviderCountryExists checks if the ProviderCountry row exists.
func ProviderCountryExists(ctx context.Context, exec boil.ContextExecutor, providerID string, countryID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"provider_country\" where \"provider_id\"=$1 AND \"country_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, providerID, countryID)
	}
	row := exec.QueryRowContext(ctx, sql, providerID, countryID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if provider_country exists")
	}

	return exists, nil
}
