// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Countries", testCountriesUpsert)

	t.Run("Histories", testHistoriesUpsert)

	t.Run("Providers", testProvidersUpsert)

	t.Run("ProviderCountries", testProviderCountriesUpsert)
}
