// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/airtime/airtime.proto

package airtime

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ProviderStatus specifies the status of a network provider
type ProviderStatus int32

const (
	ProviderStatus_Unkwown  ProviderStatus = 0
	ProviderStatus_Active   ProviderStatus = 1
	ProviderStatus_Disabled ProviderStatus = 2
)

var ProviderStatus_name = map[int32]string{
	0: "Unkwown",
	1: "Active",
	2: "Disabled",
}

var ProviderStatus_value = map[string]int32{
	"Unkwown":  0,
	"Active":   1,
	"Disabled": 2,
}

func (x ProviderStatus) String() string {
	return proto.EnumName(ProviderStatus_name, int32(x))
}

func (ProviderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{0}
}

type AddCountryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCountryRequest) Reset()         { *m = AddCountryRequest{} }
func (m *AddCountryRequest) String() string { return proto.CompactTextString(m) }
func (*AddCountryRequest) ProtoMessage()    {}
func (*AddCountryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{0}
}

func (m *AddCountryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCountryRequest.Unmarshal(m, b)
}
func (m *AddCountryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCountryRequest.Marshal(b, m, deterministic)
}
func (m *AddCountryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCountryRequest.Merge(m, src)
}
func (m *AddCountryRequest) XXX_Size() int {
	return xxx_messageInfo_AddCountryRequest.Size(m)
}
func (m *AddCountryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCountryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCountryRequest proto.InternalMessageInfo

func (m *AddCountryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddCountryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddCountryResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCountryResponse) Reset()         { *m = AddCountryResponse{} }
func (m *AddCountryResponse) String() string { return proto.CompactTextString(m) }
func (*AddCountryResponse) ProtoMessage()    {}
func (*AddCountryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{1}
}

func (m *AddCountryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCountryResponse.Unmarshal(m, b)
}
func (m *AddCountryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCountryResponse.Marshal(b, m, deterministic)
}
func (m *AddCountryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCountryResponse.Merge(m, src)
}
func (m *AddCountryResponse) XXX_Size() int {
	return xxx_messageInfo_AddCountryResponse.Size(m)
}
func (m *AddCountryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCountryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCountryResponse proto.InternalMessageInfo

func (m *AddCountryResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetCountriesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCountriesRequest) Reset()         { *m = GetCountriesRequest{} }
func (m *GetCountriesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCountriesRequest) ProtoMessage()    {}
func (*GetCountriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{2}
}

func (m *GetCountriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountriesRequest.Unmarshal(m, b)
}
func (m *GetCountriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountriesRequest.Marshal(b, m, deterministic)
}
func (m *GetCountriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountriesRequest.Merge(m, src)
}
func (m *GetCountriesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCountriesRequest.Size(m)
}
func (m *GetCountriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountriesRequest proto.InternalMessageInfo

type GetCountriesResponse struct {
	Countries            []*Country `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetCountriesResponse) Reset()         { *m = GetCountriesResponse{} }
func (m *GetCountriesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCountriesResponse) ProtoMessage()    {}
func (*GetCountriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{3}
}

func (m *GetCountriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountriesResponse.Unmarshal(m, b)
}
func (m *GetCountriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountriesResponse.Marshal(b, m, deterministic)
}
func (m *GetCountriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountriesResponse.Merge(m, src)
}
func (m *GetCountriesResponse) XXX_Size() int {
	return xxx_messageInfo_GetCountriesResponse.Size(m)
}
func (m *GetCountriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountriesResponse proto.InternalMessageInfo

func (m *GetCountriesResponse) GetCountries() []*Country {
	if m != nil {
		return m.Countries
	}
	return nil
}

type Country struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Country) Reset()         { *m = Country{} }
func (m *Country) String() string { return proto.CompactTextString(m) }
func (*Country) ProtoMessage()    {}
func (*Country) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{4}
}

func (m *Country) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Country.Unmarshal(m, b)
}
func (m *Country) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Country.Marshal(b, m, deterministic)
}
func (m *Country) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Country.Merge(m, src)
}
func (m *Country) XXX_Size() int {
	return xxx_messageInfo_Country.Size(m)
}
func (m *Country) XXX_DiscardUnknown() {
	xxx_messageInfo_Country.DiscardUnknown(m)
}

var xxx_messageInfo_Country proto.InternalMessageInfo

func (m *Country) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Country) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddProviderRequest struct {
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Logo                 string         `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	Status               ProviderStatus `protobuf:"varint,4,opt,name=status,proto3,enum=airtime.ProviderStatus" json:"status,omitempty"`
	Price                float64        `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Discount             float64        `protobuf:"fixed64,6,opt,name=discount,proto3" json:"discount,omitempty"`
	CountryId            string         `protobuf:"bytes,7,opt,name=countryId,proto3" json:"countryId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddProviderRequest) Reset()         { *m = AddProviderRequest{} }
func (m *AddProviderRequest) String() string { return proto.CompactTextString(m) }
func (*AddProviderRequest) ProtoMessage()    {}
func (*AddProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{5}
}

func (m *AddProviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProviderRequest.Unmarshal(m, b)
}
func (m *AddProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProviderRequest.Marshal(b, m, deterministic)
}
func (m *AddProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProviderRequest.Merge(m, src)
}
func (m *AddProviderRequest) XXX_Size() int {
	return xxx_messageInfo_AddProviderRequest.Size(m)
}
func (m *AddProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProviderRequest proto.InternalMessageInfo

func (m *AddProviderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddProviderRequest) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *AddProviderRequest) GetStatus() ProviderStatus {
	if m != nil {
		return m.Status
	}
	return ProviderStatus_Unkwown
}

func (m *AddProviderRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AddProviderRequest) GetDiscount() float64 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *AddProviderRequest) GetCountryId() string {
	if m != nil {
		return m.CountryId
	}
	return ""
}

type AddProviderResponse struct {
	ProviderId           string   `protobuf:"bytes,1,opt,name=providerId,proto3" json:"providerId,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProviderResponse) Reset()         { *m = AddProviderResponse{} }
func (m *AddProviderResponse) String() string { return proto.CompactTextString(m) }
func (*AddProviderResponse) ProtoMessage()    {}
func (*AddProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{6}
}

func (m *AddProviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProviderResponse.Unmarshal(m, b)
}
func (m *AddProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProviderResponse.Marshal(b, m, deterministic)
}
func (m *AddProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProviderResponse.Merge(m, src)
}
func (m *AddProviderResponse) XXX_Size() int {
	return xxx_messageInfo_AddProviderResponse.Size(m)
}
func (m *AddProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProviderResponse proto.InternalMessageInfo

func (m *AddProviderResponse) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

func (m *AddProviderResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// ProvidersRequest is a request payload for getting providers from the service
type ProvidersRequest struct {
	CountryId            string         `protobuf:"bytes,1,opt,name=countryId,proto3" json:"countryId,omitempty"`
	Status               ProviderStatus `protobuf:"varint,2,opt,name=status,proto3,enum=airtime.ProviderStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProvidersRequest) Reset()         { *m = ProvidersRequest{} }
func (m *ProvidersRequest) String() string { return proto.CompactTextString(m) }
func (*ProvidersRequest) ProtoMessage()    {}
func (*ProvidersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{7}
}

func (m *ProvidersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvidersRequest.Unmarshal(m, b)
}
func (m *ProvidersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvidersRequest.Marshal(b, m, deterministic)
}
func (m *ProvidersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvidersRequest.Merge(m, src)
}
func (m *ProvidersRequest) XXX_Size() int {
	return xxx_messageInfo_ProvidersRequest.Size(m)
}
func (m *ProvidersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvidersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvidersRequest proto.InternalMessageInfo

func (m *ProvidersRequest) GetCountryId() string {
	if m != nil {
		return m.CountryId
	}
	return ""
}

func (m *ProvidersRequest) GetStatus() ProviderStatus {
	if m != nil {
		return m.Status
	}
	return ProviderStatus_Unkwown
}

// ProvidersResponse holds the list of Providers that is returned from the Providers endpoint
type ProvidersResponse struct {
	Providers            []*Provider `protobuf:"bytes,1,rep,name=Providers,proto3" json:"Providers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProvidersResponse) Reset()         { *m = ProvidersResponse{} }
func (m *ProvidersResponse) String() string { return proto.CompactTextString(m) }
func (*ProvidersResponse) ProtoMessage()    {}
func (*ProvidersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{8}
}

func (m *ProvidersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvidersResponse.Unmarshal(m, b)
}
func (m *ProvidersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvidersResponse.Marshal(b, m, deterministic)
}
func (m *ProvidersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvidersResponse.Merge(m, src)
}
func (m *ProvidersResponse) XXX_Size() int {
	return xxx_messageInfo_ProvidersResponse.Size(m)
}
func (m *ProvidersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvidersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvidersResponse proto.InternalMessageInfo

func (m *ProvidersResponse) GetProviders() []*Provider {
	if m != nil {
		return m.Providers
	}
	return nil
}

// Provider represent a network service provider like MTN, GLO, etc.
type Provider struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CountryId            string         `protobuf:"bytes,2,opt,name=countryId,proto3" json:"countryId,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Logo                 string         `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	Status               ProviderStatus `protobuf:"varint,5,opt,name=status,proto3,enum=airtime.ProviderStatus" json:"status,omitempty"`
	Discount             float64        `protobuf:"fixed64,6,opt,name=discount,proto3" json:"discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{9}
}

func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Provider) GetCountryId() string {
	if m != nil {
		return m.CountryId
	}
	return ""
}

func (m *Provider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Provider) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Provider) GetStatus() ProviderStatus {
	if m != nil {
		return m.Status
	}
	return ProviderStatus_Unkwown
}

func (m *Provider) GetDiscount() float64 {
	if m != nil {
		return m.Discount
	}
	return 0
}

type SendAirtimeRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	ProviderId           string   `protobuf:"bytes,2,opt,name=ProviderId,proto3" json:"ProviderId,omitempty"`
	Value                float64  `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendAirtimeRequest) Reset()         { *m = SendAirtimeRequest{} }
func (m *SendAirtimeRequest) String() string { return proto.CompactTextString(m) }
func (*SendAirtimeRequest) ProtoMessage()    {}
func (*SendAirtimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{10}
}

func (m *SendAirtimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendAirtimeRequest.Unmarshal(m, b)
}
func (m *SendAirtimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendAirtimeRequest.Marshal(b, m, deterministic)
}
func (m *SendAirtimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendAirtimeRequest.Merge(m, src)
}
func (m *SendAirtimeRequest) XXX_Size() int {
	return xxx_messageInfo_SendAirtimeRequest.Size(m)
}
func (m *SendAirtimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendAirtimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendAirtimeRequest proto.InternalMessageInfo

func (m *SendAirtimeRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SendAirtimeRequest) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

func (m *SendAirtimeRequest) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type SendAirtimeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TransactionId        string   `protobuf:"bytes,3,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	Value                float64  `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendAirtimeResponse) Reset()         { *m = SendAirtimeResponse{} }
func (m *SendAirtimeResponse) String() string { return proto.CompactTextString(m) }
func (*SendAirtimeResponse) ProtoMessage()    {}
func (*SendAirtimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{11}
}

func (m *SendAirtimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendAirtimeResponse.Unmarshal(m, b)
}
func (m *SendAirtimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendAirtimeResponse.Marshal(b, m, deterministic)
}
func (m *SendAirtimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendAirtimeResponse.Merge(m, src)
}
func (m *SendAirtimeResponse) XXX_Size() int {
	return xxx_messageInfo_SendAirtimeResponse.Size(m)
}
func (m *SendAirtimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendAirtimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendAirtimeResponse proto.InternalMessageInfo

func (m *SendAirtimeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendAirtimeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SendAirtimeResponse) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *SendAirtimeResponse) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type AddProviderToCountyRequest struct {
	CountryId            string   `protobuf:"bytes,1,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	ProviderId           string   `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProviderToCountyRequest) Reset()         { *m = AddProviderToCountyRequest{} }
func (m *AddProviderToCountyRequest) String() string { return proto.CompactTextString(m) }
func (*AddProviderToCountyRequest) ProtoMessage()    {}
func (*AddProviderToCountyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{12}
}

func (m *AddProviderToCountyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProviderToCountyRequest.Unmarshal(m, b)
}
func (m *AddProviderToCountyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProviderToCountyRequest.Marshal(b, m, deterministic)
}
func (m *AddProviderToCountyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProviderToCountyRequest.Merge(m, src)
}
func (m *AddProviderToCountyRequest) XXX_Size() int {
	return xxx_messageInfo_AddProviderToCountyRequest.Size(m)
}
func (m *AddProviderToCountyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProviderToCountyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProviderToCountyRequest proto.InternalMessageInfo

func (m *AddProviderToCountyRequest) GetCountryId() string {
	if m != nil {
		return m.CountryId
	}
	return ""
}

func (m *AddProviderToCountyRequest) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

type AddProviderToCountryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProviderToCountryResponse) Reset()         { *m = AddProviderToCountryResponse{} }
func (m *AddProviderToCountryResponse) String() string { return proto.CompactTextString(m) }
func (*AddProviderToCountryResponse) ProtoMessage()    {}
func (*AddProviderToCountryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{13}
}

func (m *AddProviderToCountryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProviderToCountryResponse.Unmarshal(m, b)
}
func (m *AddProviderToCountryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProviderToCountryResponse.Marshal(b, m, deterministic)
}
func (m *AddProviderToCountryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProviderToCountryResponse.Merge(m, src)
}
func (m *AddProviderToCountryResponse) XXX_Size() int {
	return xxx_messageInfo_AddProviderToCountryResponse.Size(m)
}
func (m *AddProviderToCountryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProviderToCountryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProviderToCountryResponse proto.InternalMessageInfo

// Histories
type HistoryRequest struct {
	SkipCount            int32    `protobuf:"varint,1,opt,name=skipCount,proto3" json:"skipCount,omitempty"`
	MaxResultCount       int32    `protobuf:"varint,2,opt,name=maxResultCount,proto3" json:"maxResultCount,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryRequest) Reset()         { *m = HistoryRequest{} }
func (m *HistoryRequest) String() string { return proto.CompactTextString(m) }
func (*HistoryRequest) ProtoMessage()    {}
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{14}
}

func (m *HistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryRequest.Unmarshal(m, b)
}
func (m *HistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryRequest.Marshal(b, m, deterministic)
}
func (m *HistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryRequest.Merge(m, src)
}
func (m *HistoryRequest) XXX_Size() int {
	return xxx_messageInfo_HistoryRequest.Size(m)
}
func (m *HistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryRequest proto.InternalMessageInfo

func (m *HistoryRequest) GetSkipCount() int32 {
	if m != nil {
		return m.SkipCount
	}
	return 0
}

func (m *HistoryRequest) GetMaxResultCount() int32 {
	if m != nil {
		return m.MaxResultCount
	}
	return 0
}

func (m *HistoryRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type History struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Network              string   `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Amount               float64  `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Date                 int64    `protobuf:"varint,5,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *History) Reset()         { *m = History{} }
func (m *History) String() string { return proto.CompactTextString(m) }
func (*History) ProtoMessage()    {}
func (*History) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{15}
}

func (m *History) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_History.Unmarshal(m, b)
}
func (m *History) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_History.Marshal(b, m, deterministic)
}
func (m *History) XXX_Merge(src proto.Message) {
	xxx_messageInfo_History.Merge(m, src)
}
func (m *History) XXX_Size() int {
	return xxx_messageInfo_History.Size(m)
}
func (m *History) XXX_DiscardUnknown() {
	xxx_messageInfo_History.DiscardUnknown(m)
}

var xxx_messageInfo_History proto.InternalMessageInfo

func (m *History) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *History) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *History) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *History) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *History) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

type HistoryResponse struct {
	TotalCount           int64      `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Histories            []*History `protobuf:"bytes,2,rep,name=histories,proto3" json:"histories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *HistoryResponse) Reset()         { *m = HistoryResponse{} }
func (m *HistoryResponse) String() string { return proto.CompactTextString(m) }
func (*HistoryResponse) ProtoMessage()    {}
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{16}
}

func (m *HistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryResponse.Unmarshal(m, b)
}
func (m *HistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryResponse.Marshal(b, m, deterministic)
}
func (m *HistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryResponse.Merge(m, src)
}
func (m *HistoryResponse) XXX_Size() int {
	return xxx_messageInfo_HistoryResponse.Size(m)
}
func (m *HistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryResponse proto.InternalMessageInfo

func (m *HistoryResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *HistoryResponse) GetHistories() []*History {
	if m != nil {
		return m.Histories
	}
	return nil
}

type HistoryCountRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryCountRequest) Reset()         { *m = HistoryCountRequest{} }
func (m *HistoryCountRequest) String() string { return proto.CompactTextString(m) }
func (*HistoryCountRequest) ProtoMessage()    {}
func (*HistoryCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{17}
}

func (m *HistoryCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryCountRequest.Unmarshal(m, b)
}
func (m *HistoryCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryCountRequest.Marshal(b, m, deterministic)
}
func (m *HistoryCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryCountRequest.Merge(m, src)
}
func (m *HistoryCountRequest) XXX_Size() int {
	return xxx_messageInfo_HistoryCountRequest.Size(m)
}
func (m *HistoryCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryCountRequest proto.InternalMessageInfo

func (m *HistoryCountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type HistoryCountResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryCountResponse) Reset()         { *m = HistoryCountResponse{} }
func (m *HistoryCountResponse) String() string { return proto.CompactTextString(m) }
func (*HistoryCountResponse) ProtoMessage()    {}
func (*HistoryCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_141d63f379db254e, []int{18}
}

func (m *HistoryCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryCountResponse.Unmarshal(m, b)
}
func (m *HistoryCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryCountResponse.Marshal(b, m, deterministic)
}
func (m *HistoryCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryCountResponse.Merge(m, src)
}
func (m *HistoryCountResponse) XXX_Size() int {
	return xxx_messageInfo_HistoryCountResponse.Size(m)
}
func (m *HistoryCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryCountResponse proto.InternalMessageInfo

func (m *HistoryCountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterEnum("airtime.ProviderStatus", ProviderStatus_name, ProviderStatus_value)
	proto.RegisterType((*AddCountryRequest)(nil), "airtime.AddCountryRequest")
	proto.RegisterType((*AddCountryResponse)(nil), "airtime.AddCountryResponse")
	proto.RegisterType((*GetCountriesRequest)(nil), "airtime.GetCountriesRequest")
	proto.RegisterType((*GetCountriesResponse)(nil), "airtime.GetCountriesResponse")
	proto.RegisterType((*Country)(nil), "airtime.Country")
	proto.RegisterType((*AddProviderRequest)(nil), "airtime.AddProviderRequest")
	proto.RegisterType((*AddProviderResponse)(nil), "airtime.AddProviderResponse")
	proto.RegisterType((*ProvidersRequest)(nil), "airtime.ProvidersRequest")
	proto.RegisterType((*ProvidersResponse)(nil), "airtime.ProvidersResponse")
	proto.RegisterType((*Provider)(nil), "airtime.Provider")
	proto.RegisterType((*SendAirtimeRequest)(nil), "airtime.SendAirtimeRequest")
	proto.RegisterType((*SendAirtimeResponse)(nil), "airtime.SendAirtimeResponse")
	proto.RegisterType((*AddProviderToCountyRequest)(nil), "airtime.AddProviderToCountyRequest")
	proto.RegisterType((*AddProviderToCountryResponse)(nil), "airtime.AddProviderToCountryResponse")
	proto.RegisterType((*HistoryRequest)(nil), "airtime.HistoryRequest")
	proto.RegisterType((*History)(nil), "airtime.Histories")
	proto.RegisterType((*HistoryResponse)(nil), "airtime.HistoryResponse")
	proto.RegisterType((*HistoryCountRequest)(nil), "airtime.HistoryCountRequest")
	proto.RegisterType((*HistoryCountResponse)(nil), "airtime.HistoryCountResponse")
}

func init() { proto.RegisterFile("proto/airtime/airtime.proto", fileDescriptor_141d63f379db254e) }

var fileDescriptor_141d63f379db254e = []byte{
	// 828 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x6e, 0xd3, 0x48,
	0x14, 0xde, 0x71, 0x7e, 0x9c, 0x9c, 0x74, 0xb3, 0xe9, 0x24, 0xbb, 0xf5, 0xba, 0x69, 0x37, 0x3b,
	0xdb, 0x45, 0x11, 0x82, 0x56, 0x94, 0x8b, 0xde, 0x70, 0x53, 0x28, 0xd0, 0x0a, 0x09, 0x2a, 0x17,
	0xee, 0x90, 0x2a, 0x27, 0x1e, 0xb5, 0x56, 0x13, 0x3b, 0x78, 0xc6, 0x2d, 0x7d, 0x00, 0x6e, 0x79,
	0x13, 0x1e, 0x81, 0x87, 0xe1, 0x4d, 0x90, 0xc7, 0x33, 0xf6, 0xf8, 0x87, 0xaa, 0x57, 0xf1, 0xf9,
	0xce, 0x99, 0xf3, 0xf7, 0x9d, 0x39, 0x13, 0xd8, 0x5c, 0x45, 0x21, 0x0f, 0xf7, 0x5c, 0x3f, 0xe2,
	0xfe, 0x92, 0xaa, 0xdf, 0x5d, 0x81, 0x62, 0x53, 0x8a, 0xe4, 0x00, 0xd6, 0x0f, 0x3d, 0xef, 0x45,
	0x18, 0x07, 0x3c, 0xba, 0x75, 0xe8, 0xa7, 0x98, 0x32, 0x8e, 0xfb, 0x60, 0xf8, 0x9e, 0x85, 0x26,
	0x68, 0xda, 0x75, 0x0c, 0xdf, 0xc3, 0x18, 0x9a, 0x81, 0xbb, 0xa4, 0x96, 0x21, 0x10, 0xf1, 0x4d,
	0x76, 0x00, 0xeb, 0x07, 0xd9, 0x2a, 0x0c, 0x18, 0x2d, 0x9f, 0x24, 0x7f, 0xc2, 0xf0, 0x35, 0xe5,
	0xa9, 0x95, 0x4f, 0x99, 0x0c, 0x40, 0x5e, 0xc1, 0xa8, 0x08, 0xcb, 0xe3, 0xbb, 0xd0, 0x9d, 0x2b,
	0xd0, 0x42, 0x93, 0xc6, 0xb4, 0xb7, 0x3f, 0xd8, 0x55, 0x99, 0xab, 0x58, 0xb9, 0x09, 0x79, 0x0c,
	0xa6, 0x44, 0xef, 0x95, 0xf3, 0x77, 0x24, 0x92, 0x3e, 0x8d, 0xc2, 0x6b, 0xdf, 0xa3, 0x91, 0x2a,
	0xb7, 0xc6, 0x34, 0xc1, 0x16, 0xe1, 0x45, 0x68, 0x35, 0x52, 0x2c, 0xf9, 0xc6, 0x7b, 0xd0, 0x66,
	0xdc, 0xe5, 0x31, 0xb3, 0x9a, 0x13, 0x34, 0xed, 0xef, 0x6f, 0x64, 0xa9, 0x29, 0x8f, 0x67, 0x42,
	0xed, 0x48, 0x33, 0x3c, 0x82, 0xd6, 0x2a, 0xf2, 0xe7, 0xd4, 0x6a, 0x4d, 0xd0, 0x14, 0x39, 0xa9,
	0x80, 0x6d, 0xe8, 0x78, 0x3e, 0x13, 0x45, 0x58, 0x6d, 0xa1, 0xc8, 0x64, 0x3c, 0x56, 0x0d, 0xb8,
	0x3d, 0xf1, 0x2c, 0x53, 0xc4, 0xce, 0x01, 0xf2, 0x0e, 0x86, 0x85, 0xf4, 0x65, 0xd7, 0xb6, 0x01,
	0x56, 0x12, 0x3b, 0x51, 0x2d, 0xd0, 0x10, 0x6c, 0x81, 0xc9, 0xe2, 0xf9, 0x9c, 0x32, 0x26, 0x4a,
	0xec, 0x38, 0x4a, 0x24, 0x2e, 0x0c, 0x94, 0x37, 0xc5, 0x4d, 0x31, 0x05, 0x54, 0x4a, 0x41, 0xeb,
	0x81, 0x71, 0xaf, 0x1e, 0x90, 0x23, 0x58, 0xd7, 0x42, 0xc8, 0x8c, 0xf7, 0xa0, 0x9b, 0x81, 0x92,
	0xe7, 0xf5, 0x8a, 0x23, 0x27, 0xb7, 0x21, 0xdf, 0x10, 0x74, 0x94, 0x54, 0xa1, 0xba, 0x90, 0xb1,
	0x51, 0xce, 0x58, 0xb1, 0xdb, 0xa8, 0x61, 0xb7, 0x59, 0xcb, 0x6e, 0xeb, 0x7e, 0xec, 0xde, 0xc1,
	0x23, 0x59, 0x00, 0x3e, 0xa3, 0x81, 0x77, 0x98, 0x7a, 0x50, 0xad, 0x9d, 0x40, 0x6f, 0x75, 0x19,
	0x06, 0xf4, 0x6d, 0xbc, 0x9c, 0xd1, 0x48, 0x56, 0xa0, 0x43, 0x09, 0x95, 0xa7, 0x39, 0x95, 0x69,
	0x2d, 0x1a, 0x92, 0x4c, 0xd4, 0xb5, 0xbb, 0x88, 0xd3, 0x6a, 0x90, 0x93, 0x0a, 0xe4, 0x0b, 0x82,
	0x61, 0x21, 0x9c, 0x6c, 0xb3, 0x46, 0x3c, 0x2a, 0x10, 0x9f, 0x68, 0x96, 0x94, 0x31, 0xf7, 0x42,
	0x4d, 0xbd, 0x12, 0xf1, 0x0e, 0xfc, 0xce, 0x23, 0x37, 0x60, 0xee, 0x9c, 0xfb, 0x61, 0x70, 0xe2,
	0xc9, 0xbe, 0x15, 0xc1, 0x3c, 0x8f, 0xa6, 0x9e, 0xc7, 0x47, 0xb0, 0xb5, 0xf9, 0x7c, 0x1f, 0x8a,
	0xbb, 0x99, 0x6d, 0x95, 0x2d, 0x00, 0xc9, 0xca, 0xb9, 0x5f, 0x33, 0x59, 0xff, 0x40, 0x4f, 0xcd,
	0x6c, 0xa2, 0x37, 0xca, 0x63, 0x4c, 0xb6, 0x61, 0x5c, 0xf5, 0x9e, 0xef, 0x1e, 0x12, 0x41, 0xff,
	0xd8, 0x67, 0x3c, 0xcc, 0xf7, 0xd8, 0x18, 0xba, 0xec, 0xca, 0x5f, 0x09, 0x43, 0x11, 0xb0, 0xe5,
	0xe4, 0x00, 0x7e, 0x00, 0xfd, 0xa5, 0xfb, 0xd9, 0xa1, 0x2c, 0x5e, 0xa4, 0xab, 0x48, 0xc4, 0x6c,
	0x39, 0x25, 0x34, 0xe1, 0x39, 0x66, 0x34, 0xd2, 0x86, 0x28, 0x93, 0xc9, 0x57, 0x04, 0xa6, 0x0c,
	0x5a, 0xb0, 0x43, 0x45, 0x3b, 0xfc, 0x2f, 0xac, 0x09, 0x9a, 0xcf, 0x83, 0x94, 0x7a, 0xa3, 0x4a,
	0xbd, 0x05, 0x66, 0x40, 0xf9, 0x4d, 0x18, 0x5d, 0xc9, 0x28, 0x4a, 0xc4, 0x7f, 0x41, 0xdb, 0x5d,
	0x8a, 0x04, 0xd3, 0x6e, 0x4b, 0x29, 0x99, 0x62, 0xcf, 0xe5, 0xe9, 0x76, 0x69, 0x38, 0xe2, 0x9b,
	0xb8, 0xf0, 0x47, 0xd6, 0x84, 0x7c, 0x3d, 0xf0, 0x90, 0xbb, 0x8b, 0xbc, 0x0d, 0x0d, 0x47, 0x43,
	0x92, 0xa5, 0x7b, 0x29, 0x8e, 0x24, 0x4b, 0xd7, 0x28, 0x2d, 0x5d, 0xe5, 0x2c, 0x37, 0x21, 0x4f,
	0x60, 0x28, 0x51, 0x71, 0x5e, 0x35, 0xfb, 0x8e, 0xf2, 0xc9, 0x23, 0x18, 0x15, 0x8f, 0xc8, 0xd4,
	0x46, 0xd0, 0x9a, 0x6b, 0x59, 0xa5, 0xc2, 0xc3, 0x03, 0xe8, 0x17, 0xaf, 0x1c, 0xee, 0x81, 0xf9,
	0x21, 0xb8, 0xba, 0x09, 0x6f, 0x82, 0xc1, 0x6f, 0x18, 0xa0, 0x7d, 0x38, 0xe7, 0xfe, 0x35, 0x1d,
	0x20, 0xbc, 0x06, 0x9d, 0x23, 0x9f, 0xb9, 0xb3, 0x05, 0xf5, 0x06, 0xc6, 0xfe, 0x8f, 0x26, 0x98,
	0xf2, 0x0e, 0xe0, 0x97, 0x00, 0xf9, 0xfb, 0x84, 0xed, 0xac, 0xa0, 0xca, 0x6b, 0x67, 0x6f, 0xd6,
	0xea, 0x64, 0x86, 0xc7, 0xd0, 0xcd, 0x9e, 0x29, 0x3c, 0xce, 0x2c, 0x6b, 0x1e, 0x35, 0x7b, 0xeb,
	0x17, 0xda, 0xcc, 0x53, 0x4f, 0x1b, 0x5f, 0x5c, 0x88, 0x5a, 0x7a, 0x91, 0xec, 0x71, 0xbd, 0x52,
	0x7a, 0x7a, 0xae, 0x6d, 0x4f, 0xfc, 0x77, 0x65, 0x4d, 0x65, 0x09, 0xd9, 0x75, 0x2a, 0xe9, 0x63,
	0x06, 0xa3, 0xba, 0xcb, 0x84, 0xff, 0xab, 0x8b, 0x5c, 0xba, 0xc9, 0xf6, 0xff, 0x77, 0x18, 0x15,
	0x7a, 0xd7, 0xd3, 0xb6, 0x92, 0x56, 0x71, 0x75, 0x35, 0x6a, 0x15, 0xd7, 0x2d, 0xb2, 0x67, 0xf9,
	0x2d, 0xdb, 0xa8, 0x8c, 0xa6, 0xf4, 0x60, 0x55, 0x15, 0xf2, 0xf4, 0x1b, 0x58, 0xd3, 0xa7, 0x4f,
	0xa3, 0xb1, 0x66, 0x8e, 0x35, 0x1a, 0xeb, 0x46, 0x76, 0xd6, 0x16, 0x7f, 0xa0, 0x9e, 0xfe, 0x0c,
	0x00, 0x00, 0xff, 0xff, 0x87, 0xf1, 0x28, 0x8f, 0x5f, 0x09, 0x00, 0x00,
}
