// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testOrderStatuses(t *testing.T) {
	t.Parallel()

	query := OrderStatuses()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testOrderStatusesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderStatus{}
	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OrderStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOrderStatusesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderStatus{}
	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := OrderStatuses().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OrderStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOrderStatusesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderStatus{}
	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OrderStatusSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OrderStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOrderStatusesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderStatus{}
	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := OrderStatusExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if OrderStatus exists: %s", err)
	}
	if !e {
		t.Errorf("Expected OrderStatusExists to return true, but got false.")
	}
}

func testOrderStatusesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderStatus{}
	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	orderStatusFound, err := FindOrderStatus(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if orderStatusFound == nil {
		t.Error("want a record, got nil")
	}
}

func testOrderStatusesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderStatus{}
	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = OrderStatuses().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testOrderStatusesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderStatus{}
	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := OrderStatuses().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testOrderStatusesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	orderStatusOne := &OrderStatus{}
	orderStatusTwo := &OrderStatus{}
	if err = randomize.Struct(seed, orderStatusOne, orderStatusDBTypes, false, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}
	if err = randomize.Struct(seed, orderStatusTwo, orderStatusDBTypes, false, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = orderStatusOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = orderStatusTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OrderStatuses().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testOrderStatusesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	orderStatusOne := &OrderStatus{}
	orderStatusTwo := &OrderStatus{}
	if err = randomize.Struct(seed, orderStatusOne, orderStatusDBTypes, false, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}
	if err = randomize.Struct(seed, orderStatusTwo, orderStatusDBTypes, false, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = orderStatusOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = orderStatusTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrderStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testOrderStatusesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderStatus{}
	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrderStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOrderStatusesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderStatus{}
	if err = randomize.Struct(seed, o, orderStatusDBTypes, true); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(orderStatusColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := OrderStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOrderStatusesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderStatus{}
	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOrderStatusesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderStatus{}
	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OrderStatusSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOrderStatusesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderStatus{}
	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OrderStatuses().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	orderStatusDBTypes = map[string]string{`ID`: `character varying`, `OrderID`: `character varying`, `Status`: `character varying`, `Date`: `integer`}
	_                  = bytes.MinRead
)

func testOrderStatusesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(orderStatusPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(orderStatusAllColumns) == len(orderStatusPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OrderStatus{}
	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrderStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testOrderStatusesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(orderStatusAllColumns) == len(orderStatusPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OrderStatus{}
	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrderStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, orderStatusDBTypes, true, orderStatusPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(orderStatusAllColumns, orderStatusPrimaryKeyColumns) {
		fields = orderStatusAllColumns
	} else {
		fields = strmangle.SetComplement(
			orderStatusAllColumns,
			orderStatusPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := OrderStatusSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testOrderStatusesUpsert(t *testing.T) {
	t.Parallel()

	if len(orderStatusAllColumns) == len(orderStatusPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := OrderStatus{}
	if err = randomize.Struct(seed, &o, orderStatusDBTypes, true); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OrderStatus: %s", err)
	}

	count, err := OrderStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, orderStatusDBTypes, false, orderStatusPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OrderStatus struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OrderStatus: %s", err)
	}

	count, err = OrderStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
